%% Implementado por Daif

classDiagram
    User "1" <-- "1" Session : belongs to
    User "1" <-- "1" Account : belongs to
    User "1" <-- "*" Comment : belongs to

    class Verification {
        - id : string
        - value : string
        - expiresAt : Date
        - createdAt : Date
        - updatedAt : Date
    }

    class User {
        - id : string [PK]
        - name : string
        - email : string
        - emailVerified : bool
        - image : string
        - createdAt : Date
        - updatedAt : Date
    }

    class Session {
        - id : string [PK]
        - userId : string [FK]
        - token : string
        - expiresAt : Date
        - ipAddress : string
        - userAgent : string
        - createdAt : Date
        - updatedAt : Date
    }

    class Account {
        - id : string [PK]
        - userId : string [FK]
        - providerId : string
        - accessToken : string
        - refreshToken : string
        - accessTokenExpiresAt : Date
        - refreshTokenExpiresAt : Date
        - scope : string
        - idToken : string
        - password : string
        - createdAt : Date
        - updatedAt : Date
    }

    %% Versión normalizada de XLSX a SQL
    
    Question"1" <--"*" Comment : has many
    Question"*" <-- "1" QuestionData : through
    Category"1" --> "*" Question : has many
    Answer "*" --> "1" QuestionData : has many

    class Category {
        - id : string [PK]
        - name : string
    }

    class Question {
        - id : string [PK]
        - xlsxId : string
        - question : string
        - categoryId : string [FK]
        + getAll(...params)
        + getById(...params)
        + load(xlsxPath : string)
    }

    class QuestionData {
        - id : string [PK]
        - answerId : string [FK]
        - questionId : string [FK]
        - segmentValueId : string [FK]
    }

    Segment"1" <-- "*" SegmentValue : belongs to
    SegmentValue <-- QuestionData : belongs to

    class Segment {
        - id : string [PK]
        - name : string
    }

    class SegmentValue {
        - id : string [PK]
        - name : string
        - segmentId : string [FK]
    }

    class Answer {
        - id : string [PK]
        - answer : float
    }

    class Comment {
        - id : string [PK]
        - userId : string [FK]
        - recordId : string [FK]
        - msgContent : string
        - createdAt : Date
        + send()
    }